# Numpy

In [1]:
import numpy as np

# Creating a NumPy array without specifying data type
myarr = np.array([3, 6, 32, 7])
print(myarr)

# Creating a NumPy array with data type int8
myarr = np.array([3, 6, 32, 7], np.int8)
print(myarr)

# Creating a NumPy array with data type int64 and shape (1, 4)
myarr = np.array([[3, 6, 32, 7]], np.int64)
print(myarr)

# Accessing an element at position (0, 1)
print("Element at (0, 1):", myarr[0, 1])

# Getting the shape of the array
print("Shape of the array:", myarr.shape)

# Getting the data type of the array
print("Data type of the array:", myarr.dtype)

# Modifying an element at position (0, 1) to 45
myarr[0, 1] = 45
print("Modified array:", myarr)


[ 3  6 32  7]
[ 3  6 32  7]
[[ 3  6 32  7]]
Element at (0, 1): 6
Shape of the array: (1, 4)
Data type of the array: int64
Modified array: [[ 3 45 32  7]]


## Array creation : 

There are 5 general mechanisms for creating arrays:

1. Conversion from other Python structures (e.g., lists, tuples)

2. Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

3. Reading arrays from disk, either from standard or custom formats

4. Creating arrays from raw bytes through the use of strings or buffers

5. Use of special library functions (e.g., random)

## Examples: Conversion from other Python structures (e.g., lists, tuples)

In [2]:
import numpy as np

# Creating a NumPy array from a list of lists
listarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])
print(listarray)

# Getting the data type of the array
print("Data type of the array:", listarray.dtype)

# Getting the shape of the array
print("Shape of the array:", listarray.shape)

# Getting the total number of elements in the array
print("Size of the array:", listarray.size)


[[1 2 3]
 [5 8 5]
 [0 3 1]]
Data type of the array: int64
Shape of the array: (3, 3)
Size of the array: 9


## Examples: Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

### Zeros()

In [3]:
import numpy as np

# Creating a NumPy array of zeros with shape (2, 5)
zeros = np.zeros((2, 5))
print(zeros)

# Getting the data type of the array
print("Data type of the array:", zeros.dtype)

# Getting the shape of the array
print("Shape of the array:", zeros.shape)

# Displaying the array
print(zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Data type of the array: float64
Shape of the array: (2, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Arange()

In [4]:
import numpy as np

# Creating a NumPy array using arange() with a range of 15
rng = np.arange(15)
print(rng)

# Getting the data type of the array
print("Data type of the array:", rng.dtype)

# Getting the shape of the array
print("Shape of the array:", rng.shape)

# Displaying the array
print(rng)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Data type of the array: int64
Shape of the array: (15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Linspace()

In [5]:
import numpy as np

# Creating a NumPy array using linspace() with 4 elements between 1 and 4
lspace = np.linspace(1, 4, 4)
print(lspace)

# Getting the data type of the array
print("Data type of the array:", lspace.dtype)

# Getting the total number of elements in the array
print("Size of the array:", lspace.size)

# Getting the shape of the array
print("Shape of the array:", lspace.shape)


[1. 2. 3. 4.]
Data type of the array: float64
Size of the array: 4
Shape of the array: (4,)


## Empty()

In [6]:
import numpy as np

# Creating a NumPy array with uninitialized values using empty() with shape (4, 6)
emp = np.empty((4, 6))
print(emp)

# Getting the shape of the array
print("Shape of the array:", emp.shape)

# Getting the data type of the array
print("Data type of the array:", emp.dtype)

# Getting the total number of elements in the array
print("Size of the array:", emp.size)


[[6.30711763e-316 0.00000000e+000 1.39066290e-309 1.39066264e-309
  1.39066290e-309 1.39066264e-309]
 [1.39066290e-309 1.39066264e-309 5.34811833e-317 1.39066290e-309
  5.34806299e-317 1.39066264e-309]
 [1.39066290e-309 1.39066264e-309 1.39066290e-309 1.39066264e-309
  1.39066290e-309 1.39066264e-309]
 [5.34811833e-317 1.39066290e-309 5.34806299e-317 1.39066264e-309
  1.39066290e-309 1.39066264e-309]]
Shape of the array: (4, 6)
Data type of the array: float64
Size of the array: 24


In [7]:
import numpy as np

# Creating a NumPy array with uninitialized values using empty_like() based on lspace
emp_like = np.empty_like(lspace)
print(emp_like)

# Getting the total number of elements in the array
print("Size of the array:", emp_like.size)

# Getting the shape of the array
print("Shape of the array:", emp_like.shape)

# Getting the data type of the array
print("Data type of the array:", emp_like.dtype)


[1. 2. 3. 4.]
Size of the array: 4
Shape of the array: (4,)
Data type of the array: float64


In [8]:
import numpy as np

# Creating a 45x45 identity matrix using identity()
ide = np.identity(45)
print(ide)

# Getting the shape of the array
print("Shape of the array:", ide.shape)

# Getting the total number of elements in the array
print("Size of the array:", ide.size)

# Getting the data type of the array
print("Data type of the array:", ide.dtype)


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Shape of the array: (45, 45)
Size of the array: 2025
Data type of the array: float64


In [9]:
import numpy as np

# Creating a NumPy array using arange() with a range of 99
arr = np.arange(99)
print("Creating a NumPy array using arange() with a range of 99 :\n", arr)

# Reshaping the array to a 3x33 matrix
arr_reshaped = arr.reshape(3, 33)
print("Reshaping the array to a 3x33 matrix :\n", arr_reshaped)

# Flattening the reshaped array using ravel()
arr_ravel = arr_reshaped.ravel()
print("Flattening the reshaped array using ravel() :\n", arr_ravel)

# Getting the shape of each array
print("Shape of the original array:", arr.shape)
print("Shape of the reshaped array:", arr_reshaped.shape)
print("Shape of the flattened array:", arr_ravel.shape)


Creating a NumPy array using arange() with a range of 99 :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
Reshaping the array to a 3x33 matrix :
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
Flattening the reshaped array using ravel() :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77

In [10]:
import numpy as np

x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]
ar = np.array(x)

# Printing the original list and NumPy array
print("Original List:\n", x)
print("NumPy Array:\n", ar)

# Calculating the sum along axis 0 (columns)
print("Sum along axis 0 (columns):\n", ar.sum(axis=0))

# Calculating the sum along axis 1 (rows)
print("Sum along axis 1 (rows):\n", ar.sum(axis=1))


Original List:
 [[1, 2, 3], [4, 5, 6], [7, 1, 0]]
NumPy Array:
 [[1 2 3]
 [4 5 6]
 [7 1 0]]
Sum along axis 0 (columns):
 [12  8  9]
Sum along axis 1 (rows):
 [ 6 15  8]


In [11]:
import numpy as np

x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]
ar = np.array(x)

# Transposing the array
print("Transposed Array:\n", ar.T)

# Accessing the flattened version of the array
print("Flattened Array (using flat attribute):\n", ar.flat)

# Iterating through the flattened array
print("Iterating through the flattened array:")
for item in ar.flat:
    print(item)

# Getting the number of dimensions
print("Number of Dimensions:", ar.ndim)

# Getting the total number of elements in the array
print("Size of the array:", ar.size)

# Getting the number of bytes used by the array
print("Number of Bytes used by the array:", ar.nbytes)


Transposed Array:
 [[1 4 7]
 [2 5 1]
 [3 6 0]]
Flattened Array (using flat attribute):
Iterating through the flattened array:
1
2
3
4
5
6
7
1
0
Number of Dimensions: 2
Size of the array: 9
Number of Bytes used by the array: 72


In [12]:
import numpy as np

one = np.array([1, 3, 4, 634, 2])

# Finding the index of the maximum value
print("Index of the Maximum Value:", one.argmax())

# Finding the index of the minimum value
print("Index of the Minimum Value:", one.argmin())

# Finding the indices that would sort the array
print("Indices that would sort the array:", one.argsort())


Index of the Maximum Value: 3
Index of the Minimum Value: 0
Indices that would sort the array: [0 4 1 2 3]


In [13]:
import numpy as np

x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]
ar = np.array(x)

# Printing the original array
print("Original Array:\n", ar)

# Finding the index of the minimum value in the entire array
print("Index of the Minimum Value:", ar.argmin())

# Finding the index of the maximum value in the entire array
print("Index of the Maximum Value:", ar.argmax())

# Finding the index of the maximum value along axis 0 (columns)
print("Index of the Maximum Value along axis 0 (columns):\n", ar.argmax(axis=0))

# Finding the index of the maximum value along axis 1 (rows)
print("Index of the Maximum Value along axis 1 (rows):\n", ar.argmax(axis=1))

# Finding the indices that would sort the entire array
print("Indices that would sort the entire array:\n", ar.argsort())

# Finding the indices that would sort along axis 0 (columns)
print("Indices that would sort along axis 0 (columns):\n", ar.argsort(axis=0))

# Finding the indices that would sort along axis 1 (rows)
print("Indices that would sort along axis 1 (rows):\n", ar.argsort(axis=1))


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 1 0]]
Index of the Minimum Value: 8
Index of the Maximum Value: 6
Index of the Maximum Value along axis 0 (columns):
 [2 1 1]
Index of the Maximum Value along axis 1 (rows):
 [2 2 0]
Indices that would sort the entire array:
 [[0 1 2]
 [0 1 2]
 [2 1 0]]
Indices that would sort along axis 0 (columns):
 [[0 2 2]
 [1 0 0]
 [2 1 1]]
Indices that would sort along axis 1 (rows):
 [[0 1 2]
 [0 1 2]
 [2 1 0]]


In [14]:
import numpy as np

x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]
ar = np.array(x)

# Printing the original array
print("Original Array:\n", ar)

# Flattening the array using ravel()
print("Flattened Array using ravel():\n", ar.ravel())

# Reshaping the array to a column vector with shape (9, 1)
print("Reshaped Array to Column Vector (shape 9x1):\n", ar.reshape((9, 1)))


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 1 0]]
Flattened Array using ravel():
 [1 2 3 4 5 6 7 1 0]
Reshaped Array to Column Vector (shape 9x1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [1]
 [0]]


In [15]:
import numpy as np

ar1 = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])
ar2 = np.array([[1, 2, 1], [4, 0, 6], [8, 1, 0]])

# Printing the first array
print("Array 1:\n", ar1)

# Printing the second array
print("Array 2:\n", ar2)

# Element-wise addition of the two arrays
print("Element-wise Addition:\n", ar1 + ar2)

# Element-wise multiplication of the two arrays
print("Element-wise Multiplication:\n", ar1 * ar2)

# Element-wise subtraction of the second array from the first array
print("Element-wise Subtraction:\n", ar1 - ar2)

# Element-wise division of the first array by the second array
print("Element-wise Division:\n", ar1 / ar2)


Array 1:
 [[1 2 3]
 [4 5 6]
 [7 1 0]]
Array 2:
 [[1 2 1]
 [4 0 6]
 [8 1 0]]
Element-wise Addition:
 [[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]
Element-wise Multiplication:
 [[ 1  4  3]
 [16  0 36]
 [56  1  0]]
Element-wise Subtraction:
 [[ 0  0  2]
 [ 0  5  0]
 [-1  0  0]]
Element-wise Division:
 [[1.    1.    3.   ]
 [1.      inf 1.   ]
 [0.875 1.      nan]]


/tmp/ipykernel_8347/861573774.py:22: RuntimeWarning: divide by zero encountered in divide
  print("Element-wise Division:\n", ar1 / ar2)
/tmp/ipykernel_8347/861573774.py:22: RuntimeWarning: invalid value encountered in divide
  print("Element-wise Division:\n", ar1 / ar2)


In [16]:
import numpy as np

ar1 = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])

# Printing the original array
print("Original Array:\n", ar1)

# Calculating the square root of each element in the array
print("Square Root of the Array:\n", np.sqrt(ar1))

# Calculating the sum of all elements in the array
print("Sum of all elements in the Array:", ar1.sum())

# Finding indices where elements are greater than 5
print("Indices where elements are greater than 5:", np.where(ar1 > 5))

# Finding indices where elements are less than 3
print("Indices where elements are less than 3:", np.where(ar1 < 3))

# Getting the type of the output from np.where()
print("Type of np.where():", type(np.where(ar1 < 3)))

# Counting the number of nonzero elements in the array
print("Number of Nonzero Elements:", np.count_nonzero(ar1))

# Finding the indices of nonzero elements
print("Indices of Nonzero Elements:", np.nonzero(ar1))

# Modifying an element to create a new nonzero element
ar1[1, 2] = 0

# Finding the indices of nonzero elements after modification
print("Indices of Nonzero Elements after Modification:", np.nonzero(ar1))


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 1 0]]
Square Root of the Array:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 1.         0.        ]]
Sum of all elements in the Array: 29
Indices where elements are greater than 5: (array([1, 2]), array([2, 0]))
Indices where elements are less than 3: (array([0, 0, 2, 2]), array([0, 1, 1, 2]))
Type of np.where(): <class 'tuple'>
Number of Nonzero Elements: 8
Indices of Nonzero Elements: (array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))
Indices of Nonzero Elements after Modification: (array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))


In [17]:
import numpy as np
import sys

# Python list
py_ar = [0, 4, 55, 2]

# NumPy array
np_ar = np.array([0, 4, 55, 2])

# Calculating the size of the Python list in bytes
print("Size of Python List (in bytes):", sys.getsizeof(1) * len(py_ar))

# Calculating the size of the NumPy array in bytes
print("Size of NumPy Array (in bytes):", np_ar.itemsize * np_ar.size)


Size of Python List (in bytes): 112
Size of NumPy Array (in bytes): 32


In [18]:
import numpy as np

np_ar = np.array([0, 4, 55, 2])

# Converting NumPy array to Python list using tolist()
print("NumPy Array to Python List:", np_ar.tolist())

# Converting NumPy array to Python list using list() constructor
print("NumPy Array to Python List (alternative method):", list(np_ar))


NumPy Array to Python List: [0, 4, 55, 2]
NumPy Array to Python List (alternative method): [0, 4, 55, 2]


## Examples: Reading arrays from disk, either from standard or custom formats

Certainly! Reading arrays from disk is a common operation, and NumPy provides functions to handle various standard and custom formats. Here are examples for reading arrays from standard formats like CSV and custom formats using NumPy:

### Reading from CSV (Comma-Separated Values) File:

```python
import numpy as np

# Assume 'data.csv' contains the following data:
# 1, 2, 3
# 4, 5, 6
# 7, 8, 9

# Using np.genfromtxt to read data from a CSV file
csv_data = np.genfromtxt('data.csv', delimiter=',')

print("Array from CSV:")
print(csv_data)
```

### Reading from Custom Format:

```python
import numpy as np

# Assume 'data_custom.txt' contains the following data:
# 1;2;3
# 4;5;6
# 7;8;9

# Using np.loadtxt to read data from a file with a custom delimiter (semicolon in this case)
custom_data = np.loadtxt('data_custom.txt', delimiter=';')

print("Array from Custom Format:")
print(custom_data)
```

These are basic examples, and depending on the format of your data, you may need to adjust parameters such as delimiters, data types, etc. NumPy provides a flexible set of functions for reading various file formats, and you can explore the documentation for more options: [NumPy IO Documentation](https://numpy.org/doc/stable/reference/routines.io.html)

## Examples: Creating arrays from raw bytes through the use of strings or buffers

Certainly! You can create NumPy arrays from raw bytes using the `frombuffer` function. Here are examples of creating arrays from strings and buffers:

### Creating Array from String:

```python
import numpy as np

# Define a string of bytes
byte_string = b'\x01\x02\x03\x04\x05\x06'

# Create a NumPy array from the string
array_from_string = np.frombuffer(byte_string, dtype=np.uint8)

print("Array from String:")
print(array_from_string)
```

### Creating Array from Buffer:

```python
import numpy as np

# Create a Python byte buffer
byte_buffer = bytearray(b'\x01\x02\x03\x04\x05\x06')

# Create a NumPy array from the buffer
array_from_buffer = np.frombuffer(byte_buffer, dtype=np.uint8)

print("Array from Buffer:")
print(array_from_buffer)
```

In these examples, the `frombuffer` function is used to interpret the raw bytes and create a NumPy array. The `dtype` parameter is specified to indicate the data type of the elements in the array. Adjust the byte values and data types based on your specific use case.

## Examples: Use of special library functions (e.g., random)

Certainly! NumPy provides various special library functions, and one commonly used module is `numpy.random`. Here are examples demonstrating the use of special functions for random number generation:

### Generating Random Numbers:

```python
import numpy as np

# Generating a random float between 0 and 1
random_float = np.random.rand()
print("Random Float between 0 and 1:", random_float)

# Generating an array of random floats between 0 and 1
random_floats_array = np.random.rand(3, 2)
print("Array of Random Floats between 0 and 1:")
print(random_floats_array)

# Generating a random integer between 1 and 10
random_int = np.random.randint(1, 11)
print("Random Integer between 1 and 10:", random_int)

# Generating an array of random integers between 1 and 10
random_integers_array = np.random.randint(1, 11, size=(2, 3))
print("Array of Random Integers between 1 and 10:")
print(random_integers_array)
```

### Random Sampling:

```python
import numpy as np

# Randomly sampling from a given array
original_array = np.array([1, 2, 3, 4, 5])
random_sample = np.random.choice(original_array, size=3, replace=False)
print("Random Sample from Array:", random_sample)
```

These examples showcase basic usage of the `numpy.random` module for generating random numbers, arrays of random numbers, and random sampling from existing arrays. Adjust parameters as needed for your specific use case.

## Done: