# LECTURE 1 : Introduction to Numpy

In [1]:
# Importing the NumPy library
import numpy as np

# Printing the version of NumPy
print(np.__version__)


1.26.4


##### Command to check Jupyter running server
jupyter server list


# LECTURE 2 :  Creatng Array with Dimensions
### Now we will create a numpy ndarray object
### the array object in numpy is call ndarray
### array)

In [2]:
# Importing the NumPy library
import numpy as np

# Creating a NumPy array with elements 1, 2, 3, 4, 5
x = np.array([1, 2, 3, 4, 5]) # Through list.

# Printing the NumPy array
print(x)

# Printing the class/type of the NumPy array
print("Class of x is : ", type(x))


[1 2 3 4 5]
Class of x is :  <class 'numpy.ndarray'>


### we can also pass a list, tuple or any array like object
with array(). and it will be converted to ndarray.

In [3]:
# Importing the NumPy library
import numpy as np

# Creating a NumPy array with elements 1, 2, 3, 4, 5
y = np.array((1, 2, 3, 4, 5,)) # Through Tuple.

# Printing the NumPy array
print(y)

# Printing the type/class of the NumPy array
print("Type of y is:", type(y))


[1 2 3 4 5]
Type of y is: <class 'numpy.ndarray'>


#### Dimensions in Array
A dimensions in arrays is one level of array depth(nested array)

In [4]:
# 0-D Arrays - scalars, are the elements in an array, each value in an array is a 0-D array.
# 0-D arrays (Scalars): These are single elements, like a single number.

import numpy as np

x = np.array(42)
print(x)


42


In [5]:
# 1-D arrays - an array that has 0-D arrays as its elements is called uni directional or 1 -D
# 1-D arrays (Vectors): These have one axis.

import numpy as np

y = np.array([1, 2, 3, 4, 5])
print(y)


[1 2 3 4 5]


In [6]:
# Create a 2-D array containing 2 Arrays with certain values.
# 2-D arrays (Matrices): These have two axes, often thought of as rows and columns.
import numpy as np

z = np.array([[1, 2, 3], [4, 5, 6]])
print(z)



[[1 2 3]
 [4 5 6]]


In [7]:
# Now we will Create a 3-D array with two 2-D array.
# four. 3-D arrays: Arrays with three axes, and you can think of them as a cube of numbers.
import numpy as np

three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(three_d_array)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# Importing the NumPy library
import numpy as np

# Creating a 5-dimensional NumPy array with elements 1, 2, 3, 4, 5
five_d_array = np.array([1, 2, 3, 4, 5], ndmin=5)

# Printing the 5-dimensional NumPy array
print(five_d_array)


[[[[[1 2 3 4 5]]]]]


Note: You can have arrays with even higher dimensions as well. Understanding the dimensionality of arrays is crucial when working with NumPy, as it affects how you access and manipulate the data.

In [9]:
# Printing the number of dimensions for each array
print('Number of Dimensions', x.ndim)
print('Number of Dimensions', y.ndim)
print('Number of Dimensions', z.ndim)
print('Number of Dimensions', three_d_array.ndim)
print('Number of Dimensions', five_d_array.ndim)



Number of Dimensions 0
Number of Dimensions 1
Number of Dimensions 2
Number of Dimensions 3
Number of Dimensions 5


# LECTURE 3 :  Indexing Accessing Array Element

In [10]:
# Creating a NumPy array named pks with elements 1, 2, 3, 4
pks = np.array([1, 2, 3, 4])

# Printing the first element of the array
print(pks[0])

# Printing the last element of the array using negative indexing
print(pks[-1])


1
4


In [11]:
# Creating a NumPy array named pks with elements 1, 2, 3, 4
pks = np.array([1, 2, 3, 4])

# Printing the result of multiplying the element at index 2 with the last element
print(pks[2] * pks[-1])


12


In [12]:
# Creating a 2D NumPy array named pks_2d
pks_2d = np.array([[1, 2, 3, 4], [9, 8, 7, 6]])

# Printing the 2nd element in the first row
print('2nd element in the first row:', pks_2d[0, 1])

# Printing the 2nd element in the second row
print('2nd element in the second row:', pks_2d[1, 0])


2nd element in the first row: 2
2nd element in the second row: 9


In [13]:
# Creating a 3D NumPy array named pks_3d
pks_3d = np.array([[[1, 2, 3], [7, 8, 9]], [[4, 5, 6], [5, 4, 3]]])

# Printing the element at position (0, 1, 2) in the 3D array
print('Element at position (0, 1, 2):', pks_3d[0, 1, 2])


Element at position (0, 1, 2): 9


In [14]:
# Creating a 3D NumPy array named pks_3d
pks_3d = np.array([[[1, 2, 3], [7, 8, 9]], [[4, 5, 6], [5, 4, 3]]])

# Printing the element at position (1, 0, 2) in the 3D array
print('Element at position (1, 0, 2):', pks_3d[1, 0, 2])


Element at position (1, 0, 2): 6


# LECTURE 4 : Array Slicing

In [15]:
import numpy as np 

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing a subset of the array using slicing (indices 1 to 3)
print(x[1:4])


[2 3 4]


In [16]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing the elements from index 4 to the end of the array
print(x[4:])


[5 6 7 8 9]


In [17]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing the elements from the beginning to index 4 (exclusive)
print(x[:5])


[1 2 3 4 5]


In [18]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing the last 3 elements of the array
print(x[-3:])


[7 8 9]


In [19]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing elements from index -7 to 7 (exclusive)
print(x[-7:8])


[3 4 5 6 7 8]


In [20]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing elements from the third-to-last to the second-to-last (inclusive)
print(x[-3:-1])


[7 8]


## Indexing using Steps : 

In [21]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing every second element from index 1 to 6 (exclusive)
print(x[1:7:2])


[2 4 6]


In [22]:
import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing every second element in the entire array
print(x[::2])


[1 3 5 7 9]


In [23]:

import numpy as np

# Creating a NumPy array with elements 1 to 9
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Printing every third element of the array
print(x[::3])


[1 4 7]


In [24]:
# Slicing 2-D Array
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Slicing the second row from index 1 to 3 (exclusive)
print(x[1, 1:4])


[7 8 9]


In [25]:
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Slicing elements from the first row (index 0) in the third to the last columns
# Slicing elements from the second row (index 1) in the first three columns
print(x[0, 2:], x[1, 0:3])


[3 4 5] [6 7 8]


In [26]:
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Slicing elements from the second row (index 1) in the third to the last columns
# Slicing elements from the first row (index 0) in the second and third columns
print(x[1, 2:], x[0, 1:3])


[ 8  9 10] [2 3]


In [27]:
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Printing elements from the third column for both rows (indices 0 and 1)
print(x[0:2, 2])



[3 8]


In [28]:
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Printing specific elements from the first row (index 0) in the third column
# and from the second row (index 1) in the third column
print(x[0, 2], x[1, 2])


3 8


In [29]:
import numpy as np

# Creating a 2-D NumPy array
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Printing a subset of elements by slicing rows (indices 0 and 1) and columns (indices 1 to 3)
print(x[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [30]:
import numpy as np

# Creating a 3-D NumPy array
x = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[8, 9, 0, 1], [3, 2, 8, 9]]])

# Extracting elements 2 and 3 from each subarray
result = x[:, :, 1:3]

print(result)

[[[2 3]
  [6 7]]

 [[9 0]
  [2 8]]]


# LECTURE 5: NUMPY DATATYPES

**DATA TYPES IN PYTHON:**
* STRING
* INTEGER
* FLOAT
* BOOLEAN
* COMPLEX

**DATA TYPES IN NUMPY:**
* `i` for integer
* `b` for boolean
* `u` for unsigned integer
* `f` for float
* `c` for complex float
* `m` for timedelta
* `M` for datetime
* `O` for object
* `S` for string
* `U` for unicode string
* `V` for memory


In [31]:
import numpy as np

# Integer data type
int_arr = np.array([1, 2, 3])
print("Integer array:", int_arr, "dtype:", int_arr.dtype)

# Boolean data type
bool_arr = np.array([True, False, True])
print("Boolean array:", bool_arr, "dtype:", bool_arr.dtype)

# Unsigned integer data type
uint_arr = np.array([0, 1, 2], dtype=np.uint)
print("Unsigned integer array:", uint_arr, "dtype:", uint_arr.dtype)

# Float data type
float_arr = np.array([1.0, 2.5, 3.7])
print("Float array:", float_arr, "dtype:", float_arr.dtype)

# Complex float data type
complex_arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print("Complex float array:", complex_arr, "dtype:", complex_arr.dtype)

# Timedelta data type
timedelta_arr = np.array([np.timedelta64(1, 'D'), np.timedelta64(2, 'D'), np.timedelta64(3, 'D')])
print("Timedelta array:", timedelta_arr, "dtype:", timedelta_arr.dtype)

# Datetime data type
datetime_arr = np.array(['2022-01-01', '2022-01-02', '2022-01-03'], dtype='datetime64')
print("Datetime array:", datetime_arr, "dtype:", datetime_arr.dtype)

# Object data type
object_arr = np.array(['a', 1, 2.5])
print("Object array:", object_arr, "dtype:", object_arr.dtype)

# String data type
str_arr = np.array(['hello', 'world'])
print("String array:", str_arr, "dtype:", str_arr.dtype)

# Unicode string data type (Hindi and Sanskrit)
unicode_arr = np.array(['नमस्ते', 'नमस्कार'], dtype='U')
print("Unicode string array:", unicode_arr, "dtype:", unicode_arr.dtype)

# Memory data type
memory_arr = np.array([b'abc', b'def'])
print("Memory array:", memory_arr, "dtype:", memory_arr.dtype)


Integer array: [1 2 3] dtype: int64
Boolean array: [ True False  True] dtype: bool
Unsigned integer array: [0 1 2] dtype: uint64
Float array: [1.  2.5 3.7] dtype: float64
Complex float array: [1.+2.j 3.+4.j 5.+6.j] dtype: complex128
Timedelta array: [1 2 3] dtype: timedelta64[D]
Datetime array: ['2022-01-01' '2022-01-02' '2022-01-03'] dtype: datetime64[D]
Object array: ['a' '1' '2.5'] dtype: <U32
String array: ['hello' 'world'] dtype: <U5
Unicode string array: ['नमस्ते' 'नमस्कार'] dtype: <U7
Memory array: [b'abc' b'def'] dtype: |S3


In [32]:
import numpy as np

# Creating a NumPy array with elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the data type of the array
print("Data type of the array x:", x.dtype)

# Printing the array x
print("Array x:", x)


Data type of the array x: int64
Array x: [1 2 3 4]


In [33]:
import numpy as np

# Creating a NumPy array with string elements
y = np.array(['Praveen', 'Rahul', 'Priyanka'])

# Printing the data type of the array
print("Data type of the array y:", y.dtype)

# Printing the array y
print("Array y:", y)


Data type of the array y: <U8
Array y: ['Praveen' 'Rahul' 'Priyanka']


In [34]:
import numpy as np

# Creating a NumPy array with elements 1, 2, 3, and 4 and specifying dtype as string
x = np.array([1, 2, 3, 4], dtype='S')

# Printing the data type of the array
print("Data type of the array x:", x.dtype)

# Printing the array x
print("Array x:", x)


Data type of the array x: |S1
Array x: [b'1' b'2' b'3' b'4']


In [35]:
import numpy as np

# Creating a NumPy array with string elements '4', '1', '3' and specifying dtype as integer
x = np.array(['4', '1', '3'], dtype='i')

# Printing the data type of the array
print("Data type of the array x:", x.dtype)

# Printing the array x
print("Array x:", x)


Data type of the array x: int32
Array x: [4 1 3]


In [36]:
import numpy as np

# Creating a NumPy array with float elements
x = np.array([1.1, 2.3, 4.8])

# Converting the array x to integer type
y = x.astype('i')

# Printing the data type and array for original array x
print("Data type of the array x:", x.dtype)
print("Array x:", x)

# Printing the data type and array for converted array y
print("Data type of the array y:", y.dtype)
print("Array y:", y)


Data type of the array x: float64
Array x: [1.1 2.3 4.8]
Data type of the array y: int32
Array y: [1 2 4]


In [37]:
import numpy as np

# Creating a NumPy array with integer elements
x = np.array([1, 0, 3, 4, 5])

# Converting the array x to boolean type
y = x.astype(bool)

# Converting the array x to float type
z = x.astype(float)

# Printing the original array x
print("Original array x:", x)

# Printing the array y with boolean elements
print("Array y (boolean type):", y)

# Printing the array z with float elements
print("Array z (float type):", z)

# Printing the data type of each array
print("Data type of array x:", x.dtype)
print("Data type of array y:", y.dtype)
print("Data type of array z:", z.dtype)


Original array x: [1 0 3 4 5]
Array y (boolean type): [ True False  True  True  True]
Array z (float type): [1. 0. 3. 4. 5.]
Data type of array x: int64
Data type of array y: bool
Data type of array z: float64
