# LECTURE 11: NumPy Splitting Array
* spliting arrays in numpy- it is reverse to joining, breaking the array.
* array_split()

In [1]:
# split the array in 3 parts:

import numpy as np

# Creating a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 subarrays
result = np.split(arr, 3)

# Printing the result
print("Split result:", result)

Split result: [array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
import numpy as np

# Creating a 1D array with 8 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Splitting the array into 4 subarrays
result = np.split(arr, 4)

# Printing the result
print("Split result:", result)


Split result: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


If you've seen an example where someone successfully split an array into an uneven number of subarrays, it's possible that they used a different function or approach. While `np.split()` requires an equal division, there are other functions in NumPy that can handle uneven splits or provide more flexibility in splitting arrays.

One alternative is `np.array_split()`, which can handle uneven splits by creating subarrays with varying sizes to accommodate the uneven division:

```python
import numpy as np

# Creating a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 4 subarrays (uneven division allowed)
result = np.array_split(arr, 4)

# Printing the result
print("Split result:", result)
```

This will split the array into 4 subarrays, allowing for uneven division if the array size is not perfectly divisible by the number of splits.

In [3]:
# Spliting into array with index
import numpy as np

# Create a NumPy array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 subarrays
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:", result[0])

# Print the second subarray resulting from the split
print("Second subarray:", result[1])

# Print the third subarray resulting from the split
print("Third subarray:", result[2])


First subarray: [1 2]
Second subarray: [3 4]
Third subarray: [5 6]


In [4]:
# Splitting the 2-D array into three 2D Array
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2]
 [3 4]]
Second subarray:
 [[5 6]
 [7 8]]
Third subarray:
 [[ 9 10]
 [11 12]]


In [5]:
# Splitting the 2-D array into three 2D arrays
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2 3]
 [4 5 6]]
Second subarray:
 [[ 7  8  9]
 [10 11 12]]
Third subarray:
 [[13 14 15]
 [16 17 18]]


In [6]:
# Splitting the 2-D array into three 2D Arrays along with rows
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3, axis=1)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Second subarray:
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Third subarray:
 [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [7]:
# Alternate solution using hsplit(), opposite hstack()
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.hsplit(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Second subarray:
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Third subarray:
 [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [8]:
# Using vsplit() to split along the vertical axis
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Split the array into 3 subarrays along the vertical axis
result = np.vsplit(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2]
 [3 4]]
Second subarray:
 [[5 6]
 [7 8]]
Third subarray:
 [[ 9 10]
 [11 12]]


In [9]:
# Using dstack() to stack arrays along the third axis
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Stack the arrays along the third axis
result = np.dstack((arr1, arr2))

# Print the resulting stacked array
print("Stacked array along the third axis:\n", result)


Stacked array along the third axis:
 [[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]

 [[ 7 16]
  [ 8 17]
  [ 9 18]]]


# 12. NumPy Searching Array || where & searchsorted

# 13. NumPy Sorting Array || Sort() 1D, 2D, 3D Array 

# 14. NumPy Filter Array || Creating the Filter Array

# 15. NumPy Random Numbers || rand() randint() choice() 