# LECTURE 11: NumPy Splitting Array
* spliting arrays in numpy- it is reverse to joining, breaking the array.
* array_split()

In [1]:
# split the array in 3 parts:

import numpy as np

# Creating a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 3 subarrays
result = np.split(arr, 3)

# Printing the result
print("Split result:", result)

Split result: [array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
import numpy as np

# Creating a 1D array with 8 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Splitting the array into 4 subarrays
result = np.split(arr, 4)

# Printing the result
print("Split result:", result)


Split result: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


If you've seen an example where someone successfully split an array into an uneven number of subarrays, it's possible that they used a different function or approach. While `np.split()` requires an equal division, there are other functions in NumPy that can handle uneven splits or provide more flexibility in splitting arrays.

One alternative is `np.array_split()`, which can handle uneven splits by creating subarrays with varying sizes to accommodate the uneven division:

```python
import numpy as np

# Creating a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into 4 subarrays (uneven division allowed)
result = np.array_split(arr, 4)

# Printing the result
print("Split result:", result)
```

This will split the array into 4 subarrays, allowing for uneven division if the array size is not perfectly divisible by the number of splits.

In [3]:
# Spliting into array with index
import numpy as np

# Create a NumPy array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Split the array into 3 subarrays
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:", result[0])

# Print the second subarray resulting from the split
print("Second subarray:", result[1])

# Print the third subarray resulting from the split
print("Third subarray:", result[2])


First subarray: [1 2]
Second subarray: [3 4]
Third subarray: [5 6]


In [4]:
# Splitting the 2-D array into three 2D Array
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2]
 [3 4]]
Second subarray:
 [[5 6]
 [7 8]]
Third subarray:
 [[ 9 10]
 [11 12]]


In [5]:
# Splitting the 2-D array into three 2D arrays
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2 3]
 [4 5 6]]
Second subarray:
 [[ 7  8  9]
 [10 11 12]]
Third subarray:
 [[13 14 15]
 [16 17 18]]


In [6]:
# Splitting the 2-D array into three 2D Arrays along with rows
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.array_split(arr, 3, axis=1)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Second subarray:
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Third subarray:
 [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [7]:
# Alternate solution using hsplit(), opposite hstack()
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Split the array into 3 subarrays along the rows
result = np.hsplit(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
Second subarray:
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
Third subarray:
 [[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [8]:
# Using vsplit() to split along the vertical axis
import numpy as np

# Create a NumPy array with 6 rows and 2 columns
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Split the array into 3 subarrays along the vertical axis
result = np.vsplit(arr, 3)

# Print the first subarray resulting from the split
print("First subarray:\n", result[0])

# Print the second subarray resulting from the split
print("Second subarray:\n", result[1])

# Print the third subarray resulting from the split
print("Third subarray:\n", result[2])


First subarray:
 [[1 2]
 [3 4]]
Second subarray:
 [[5 6]
 [7 8]]
Third subarray:
 [[ 9 10]
 [11 12]]


In [9]:
# Using dstack() to stack arrays along the third axis
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Stack the arrays along the third axis
result = np.dstack((arr1, arr2))

# Print the resulting stacked array
print("Stacked array along the third axis:\n", result)


Stacked array along the third axis:
 [[[ 1 10]
  [ 2 11]
  [ 3 12]]

 [[ 4 13]
  [ 5 14]
  [ 6 15]]

 [[ 7 16]
  [ 8 17]
  [ 9 18]]]


# 12. NumPy Searching Array || where & searchsorted

In [10]:
import numpy as np

# searching array - you can search an array for a certain value and return the indexes that get the match. by using where
# Create a NumPy array with 6 rows and 2 columns
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Search for the value 4 in the array and return the indices where it occurs
result = np.where(arr == 4)

# Print the indices where the value 4 occurs
print("Indices where the value 4 occurs:", result)


Indices where the value 4 occurs: (array([3, 5, 6]),)


In [11]:
import numpy as np

# Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Use np.where() to find the indices where the values are even
result = np.where(arr % 2 == 0)

# Print the indices where the values are even
print("Indices where the values are even:", result)


Indices where the values are even: (array([1, 3, 5, 7]),)


In [12]:
import numpy as np

# Find the indexes where the values are odd
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Use np.where() to find the indices where the values are odd
result = np.where(arr % 2 == 1)

# Print the indices where the values are odd
print("Indices where the values are odd:", result)


Indices where the values are odd: (array([0, 2, 4, 6]),)


In [13]:
import numpy as np

# Perform a binary search to find the index where
# the value 7 should be inserted into the sorted array
arr = np.array([6, 7, 8, 9])
result = np.searchsorted(arr, 7)

print("Index where 7 should be inserted:", result)


Index where 7 should be inserted: 1


In [14]:
import numpy as np

# Perform a binary search from the right side
arr = np.array([6, 7, 8, 9])
result = np.searchsorted(arr, 7, side='right')

print("Index where 7 should be inserted (from right side):", result)


Index where 7 should be inserted (from right side): 2


In [15]:
import numpy as np

# Search for multiple values
arr = np.array([1, 3, 5, 7])
result = np.searchsorted(arr, [2, 4, 6])

print("Indexes where values should be inserted:", result)


Indexes where values should be inserted: [1 2 3]


# 13. NumPy Sorting Array || Sort() 1D, 2D, 3D Array 

In [16]:
import numpy as np

# Sort the array
arr = np.array([3, 2, 0, 1])
result = np.sort(arr)

print("Sorted array:", result) # this mathod is like the copy()


Sorted array: [0 1 2 3]


In [17]:
import numpy as np

# Sort the array alphabetically
arr = np.array(['banana', 'cherry', 'apple'])
result = np.sort(arr)

print("Sorted array:", result)


Sorted array: ['apple' 'banana' 'cherry']


In [18]:
import numpy as np

# Sort the boolean array
arr = np.array([True, False, False, True, False])
result = np.sort(arr)

print("Sorted array:", result)


Sorted array: [False False False  True  True]


In [19]:
import numpy as np

# Sort the 2-D array along each row
arr = np.array([[3, 2, 4], [5, 0, 1]])
result = np.sort(arr)

print("Sorted array along each row:\n", result)


Sorted array along each row:
 [[2 3 4]
 [0 1 5]]


# 14. NumPy Filter Array || Creating the Filter Array

* Getting some elements out of an existing array and creating a new array is called filtering.
* A boolean index list is a list ofboolean corresponding to indexes in the array. (True and False)

In [20]:
import numpy as np

# Create an array from the elements at index 0 and 2
arr = np.array([41, 42, 43, 44])
mask = [True, False, True, False]

result = arr[mask]
print("Array using indexing:", result)


Array using indexing: [41 43]


In [21]:
import numpy as np

# Create a filter array that will return only values higher than 42
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
result = arr[filter_arr]
print("Filter array:", filter_arr)
print("Result array:", result)


Filter array: [False, False, True, True]
Result array: [43 44]


In [22]:
import numpy as np

# Create a filter array that will return only even elements from the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []

for i in arr:
    if i % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
result = arr[filter_arr]
print("Filter array:", filter_arr)
print("Result array:", result)


Filter array: [False, True, False, True, False, True, False]
Result array: [2 4 6]


In [23]:
import numpy as np

# Creating a filter directly from the array to return only values higher than 42
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42
result = arr[filter_arr]

print("Filter array:", filter_arr)
print("Result array:", result)


Filter array: [False False  True  True]
Result array: [43 44]


In [24]:
import numpy as np

# Creating a filter directly from the array to return only even elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0
result = arr[filter_arr]

print("Filter array:", filter_arr)
print("Result array:", result)


Filter array: [False  True False  True False  True False]
Result array: [2 4 6]


# 15. NumPy Random Numbers || rand() randint() choice() 

* Random meaning - something that cannot be predicted logically
* Now we will generate a random number


In [25]:
import numpy as np

# Generating random numbers between 0 and 1
random_numbers = np.random.rand(3, 3)
print("Random numbers between 0 and 1:")
print(random_numbers)

# Generating random integers between specified range
random_integers = np.random.randint(1, 100, size=(2, 3))
print("\nRandom integers between 1 and 100:")
print(random_integers)

# Selecting random elements from a given array
array = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
random_choice = np.random.choice(array, size=3)
print("\nRandom choice from the array:")
print(random_choice)


Random numbers between 0 and 1:
[[0.03061717 0.43712408 0.53911058]
 [0.57928092 0.49803176 0.86607936]
 [0.92138914 0.39534584 0.98944828]]

Random integers between 1 and 100:
[[85 93 95]
 [67  1 90]]

Random choice from the array:
['cherry' 'cherry' 'banana']


In [26]:
from numpy import random

# Generate a random integer between 0 and 100
random_int = random.randint(100)
print("Random integer:", random_int)


Random integer: 62


In [27]:
from numpy import random

# Generate a random float between 0 and 1
random_float = random.rand()
print("Random float:", random_float)


Random float: 0.9512820049115321


In [28]:
from numpy import random

# Generate a 1-D array containing 5 random integers from 0 to 100
random_arr = random.randint(100, size=(5))
print("Random array:", random_arr)


Random array: [77 93 82  9 26]


In [29]:
from numpy import random

# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
random_arr_2D = random.randint(100, size=(3, 5))
print("Random 2D array:\n", random_arr_2D)


Random 2D array:
 [[39 69 91 63 12]
 [91  2 56  6 25]
 [ 4  4 57 39 13]]


In [30]:
from numpy import random

# Generate a 1-D array containing 5 random floats
random_arr_1D = random.rand(5)
print("Random 1D array:", random_arr_1D)


Random 1D array: [0.92785373 0.67752528 0.24431917 0.03627779 0.01018949]


In [31]:
from numpy import random

# Generate a 2-D array with 3 rows, each row containing 5 random floats
random_arr_2D = random.rand(3, 5)
print("Random 2D array:\n", random_arr_2D)


Random 2D array:
 [[0.01557209 0.68831716 0.36544864 0.52060145 0.33467629]
 [0.95047915 0.18751203 0.75583784 0.95954801 0.85430154]
 [0.3688436  0.72992553 0.57020969 0.10875592 0.8117711 ]]


In [32]:
from numpy import random

# Generate a random number from the provided array
random_choice = random.choice([3, 5, 7, 9, 1, 4, 6])
print("Random choice:", random_choice)


Random choice: 3


In [33]:
from numpy import random

# Generate a 2D array of random numbers from the provided array
random_choice = random.choice([3, 5, 7, 9, 1, 4, 6], size=(3, 5))
print("Random choice:\n", random_choice)


Random choice:
 [[3 1 1 5 4]
 [9 3 1 6 7]
 [9 3 1 4 3]]
