## Numpy Array Slicing

#### slicing array - slicing in python means taking elemetns from one given index to another index.  [start:end], [start:end:step]

In [1]:
# now we will slice an element from 1 to 5 :
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sharad[1:5])

[2 3 4 5]


In [2]:
# now we will slice from index 4 to the end value
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sharad[4:])

[5 6 7 8 9]


In [3]:
# now we will slice the element from the begining to index 4
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sharad[:4])

[1 2 3 4]


In [4]:
# Negative Slicing - index 3 to end
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7])
print(sharad[-3:-1])

[5 6]


In [5]:
# Step: you will use step value to determine the step of the slicing
# return every other value from index 1 to 5
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7])
print(sharad[1:5:2])


[2 4]


In [6]:
# now return every other number from the entire array
import numpy as np
sharad = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(sharad[::2])

[1 3 5 7 9]


In [7]:
# slicing 2-D Array: print 7,8,9
import numpy as np
sharad = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(sharad[1,1:4])

[7 8 9]


In [8]:
# another example : 4th element of each List
import numpy as np
sharad = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(sharad[0:2 , 4])

[ 5 10]


In [9]:
# another example tough 2-D - print from both, index 1:4
import numpy as np
sharad = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(sharad[0:2 , 1:4])


[[2 3 4]
 [7 8 9]]
