# 31.NumPy Create Your Own ufunc || frompyfunc() or np.ufunc

To create your own ufunc in NumPy, you can use `frompyfunc()` or `np.ufunc`. Below is an example of how to create a simple ufunc using `frompyfunc()`:

```python
import numpy as np

# Define a custom function
def my_func(x):
    return x ** 2 + 2 * x + 1

# Create a ufunc from the custom function using frompyfunc()
my_ufunc = np.frompyfunc(my_func, 1, 1)

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Apply the custom ufunc to the array
result = my_ufunc(arr)

print("Result:", result)
```

In this example, we define a custom function `my_func(x)` that calculates the quadratic expression `x^2 + 2x + 1`. We then create a ufunc `my_ufunc` from this custom function using `frompyfunc()`. Finally, we apply the ufunc to a NumPy array `arr` and print the result.

Alternatively, you can create a ufunc using the `np.vectorize()` decorator or by subclassing `np.ufunc`. Both approaches allow you to define element-wise operations on arrays in a more efficient manner than traditional Python loops.

## Sharad :
To create your own ufunc in NumPy, you first define a function similar to how you would define a normal Python function. Then, you add it to NumPy using the `frompyfunc()` method.

The arguments of `frompyfunc()` are:
- The function you want to convert into a ufunc.
- The number of input arguments the function takes.
- The number of output arguments the function produces.


```

This will output:
```
[5 7 9]
```

Here, `custom_add` is a custom addition function taking two input arguments (`x` and `y`) and returning their sum. `np.frompyfunc(custom_add, 2, 1)` converts this function into a ufunc that takes two input arguments and produces one output.

In [1]:
# Here's how you can create your own ufunc for addition:


import numpy as np

# Define your custom addition function
def custom_add(x, y):
    return x + y

# Convert the custom function to a ufunc using frompyfunc
add_ufunc = np.frompyfunc(custom_add, 2, 1)

# Test the ufunc with NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = add_ufunc(arr1, arr2)

print(result)

[5 7 9]


In [1]:
# Create your own ufunc for addition :
import numpy as np

# Define a custom function
def my_add_function(x, y):
    return x + y

# Create a ufunc from the custom function using frompyfunc()
my_add_ufunc = np.frompyfunc(my_add_function, 2, 1)

# Use the custom ufunc on arrays
result = my_add_ufunc([1, 2, 3, 4], [5, 6, 7, 8])

print("Result:", result)


Result: [6 8 10 12]


Your code checks the types of three functions: `np.add`, `np.concatenate`, and `np.asdfdsf`. It correctly identifies `np.add` and `np.concatenate` as ufuncs but will raise an error for `np.asdfdsf` since it is not a valid NumPy function.

Here's the corrected code:

```python
import numpy as np

print(type(np.add))  # Output: <class 'numpy.ufunc'>
print(type(np.concatenate))  # Output: <class 'function'>

# Attempting to check the type of an invalid function
try:
    print(type(np.asdfdsf))
except AttributeError as e:
    print(f"Error: {e}")

if type(np.add) == np.ufunc:
    print('Yes, this function is a ufunc')
else:
    print('This function is not a ufunc')
```

This code will correctly handle the case where an invalid function like `np.asdfdsf` is encountered.


In [2]:
import numpy as np

print(type(np.add))  # Output: <class 'numpy.ufunc'>
print(type(np.concatenate))  # Output: <class 'function'>

# Attempting to check the type of an invalid function
try:
    print(type(np.asdfdsf))
except AttributeError as e:
    print(f"Error: {e}")

if type(np.add) == np.ufunc:
    print('Yes, this function is a ufunc')
else:
    print('This function is not a ufunc')

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>
Error: module 'numpy' has no attribute 'asdfdsf'
Yes, this function is a ufunc


# 32.NumPy Arithmetic ufunc || add() subtract() multiply() divide() 

Certainly! Here's the corrected sentence:


### Arithmetic operators: +, -, /, 
### By using ufunc, additional arguments such as where, dtype, and out can be employed.


NumPy provides several arithmetic ufuncs for performing element-wise operations on arrays. Here are some commonly used ones:

1. **Addition:**
   - `np.add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`: Add arguments element-wise.

```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_add = np.add(arr1, arr2)
print("Addition Result:", result_add)
```

2. **Subtraction:**
   - `np.subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`: Subtract arguments element-wise.

```python
import numpy as np

arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])

result_subtract = np.subtract(arr1, arr2)
print("Subtraction Result:", result_subtract)
```

3. **Multiplication:**
   - `np.multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`: Multiply arguments element-wise.

```python
import numpy as np

arr1 = np.array([2, 3, 4])
arr2 = np.array([5, 6, 7])

result_multiply = np.multiply(arr1, arr2)
print("Multiplication Result:", result_multiply)
```

4. **Division:**
   - `np.divide(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])`: Divide arguments element-wise.

```python
import numpy as np

arr1 = np.array([8, 10, 12])
arr2 = np.array([2, 5, 3])

result_divide = np.divide(arr1, arr2)
print("Division Result:", result_divide)
```

These functions allow you to perform arithmetic operations on NumPy arrays in an element-wise manner.

# Sharad :
## np.add()
Certainly! Here's your code with comments explaining each section:

```python
# Importing the NumPy library
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 11, 12, 12, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Using np.add() to perform element-wise addition on the arrays
result_add = np.add(arr1, arr2)

# Printing the result of the addition
print("Addition Result:", result_add)
```

Explanation of comments:

- `import numpy as np`: Imports the NumPy library and gives it the alias `np` for easier reference.

- `arr1 = np.array([10, 11, 12, 12, 14, 15])`: Creates a NumPy array `arr1` with the specified elements.

- `arr2 = np.array([20, 21, 22, 23, 24, 25])`: Creates another NumPy array `arr2` with the specified elements.

- `result_add = np.add(arr1, arr2)`: Uses the `np.add()` function to perform element-wise addition on `arr1` and `arr2`, storing the result in the `result_add` variable.

- `print("Addition Result:", result_add)`: Prints the result of the addition operation.

This code snippet demonstrates the use of `np.add` for element-wise addition of two NumPy arrays and prints the resulting array.

## np.subtract()

It seems there is a small mistake in your comment. Your code is performing subtraction, not addition. Here's the corrected comment and code:

```python
# Example of subtracting the values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 11, 12, 12, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Using np.subtract() to perform element-wise subtraction on arr2 - arr1
result_subtract = np.subtract(arr2, arr1)

# Printing the result of the subtraction
print("Subtraction Result:", result_subtract)
```

Explanation:

- `result_subtract = np.subtract(arr2, arr1)`: Uses the `np.subtract()` function to perform element-wise subtraction (`arr2 - arr1`), storing the result in the `result_subtract` variable.

- `print("Subtraction Result:", result_subtract)`: Prints the result of the subtraction operation.

## np.multiply()
It appears there is a small mistake in your comment. Your code is performing multiplication, not addition. Here's the corrected comment and code:

```python
# Example of multiplying the values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 11, 12, 12, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Using np.multiply() to perform element-wise multiplication on arr2 * arr1
result_multiply = np.multiply(arr2, arr1)

# Printing the result of the multiplication
print("Multiplication Result:", result_multiply)
```

Explanation:

- `result_multiply = np.multiply(arr2, arr1)`: Uses the `np.multiply()` function to perform element-wise multiplication (`arr2 * arr1`), storing the result in the `result_multiply` variable.

- `print("Multiplication Result:", result_multiply)`: Prints the result of the multiplication operation.

## np.divide()
It looks like there is a small mistake in your comment. Your code is performing division, not addition. Here's the corrected comment and code:

```python
# Example of dividing the values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 11, 12, 12, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Using np.divide() to perform element-wise division on arr2 / arr1
result_divide = np.divide(arr2, arr1)

# Printing the result of the division
print("Division Result:", result_divide)
```

Explanation:

- `result_divide = np.divide(arr2, arr1)`: Uses the `np.divide()` function to perform element-wise division (`arr2 / arr1`), storing the result in the `result_divide` variable.

- `print("Division Result:", result_divide)`: Prints the result of the division operation.

### The power() function raises the values from the first array to the power of the corresponding values in the second array and returns the results in a new array.


It seems there's a mistake in your comment. Your code is not performing addition; it's actually using the `np.power()` function to calculate the power of elements in `arr2` to the corresponding elements in `arr1`. Here's the corrected comment and code:

```python
# Example of calculating the power of values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

# Using np.power() to calculate element-wise power arr2^arr1
result_power = np.power(arr2, arr1)

# Printing the result of the power calculation
print("Power Result:", result_power)
```

Explanation:

- `result_power = np.power(arr2, arr1)`: Uses the `np.power()` function to calculate element-wise power (`arr2^arr1`), storing the result in the `result_power` variable.

- `print("Power Result:", result_power)`: Prints the result of the power calculation.

### The remainder-mod() and remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, resulting in a new array.


There seems to be a misunderstanding in your comment. Your code is not performing addition; it's using the `np.mod()` function to calculate the element-wise remainder of the division of elements in `arr1` by the corresponding elements in `arr2`. Here's the corrected comment and code:

```python
# Example of calculating the remainder (modulus) of values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

# Using np.mod() to calculate element-wise remainder of arr1 mod arr2
result_remainder = np.mod(arr1, arr2)

# Printing the result of the modulus calculation
print("Modulus Result:", result_remainder)
```

Explanation:

- `result_remainder = np.mod(arr1, arr2)`: Uses the `np.mod()` function to calculate the element-wise remainder of the division of `arr1` by `arr2`, storing the result in the `result_remainder` variable.

- `print("Modulus Result:", result_remainder)`: Prints the result of the modulus calculation.

## Using np.remainder()

It seems there is a mistake in your comment. Your code is not performing addition; it's using the `np.remainder()` function to calculate the element-wise remainder of the division of elements in `arr1` by the corresponding elements in `arr2`. Here's the corrected comment and code:

```python
# Example of calculating the remainder (modulus) of values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

# Using np.remainder() to calculate element-wise remainder of arr1 mod arr2
result_remainder = np.remainder(arr1, arr2)

# Printing the result of the modulus calculation
print("Remainder Result:", result_remainder)
```

Explanation:

- `result_remainder = np.remainder(arr1, arr2)`: Uses the `np.remainder()` function to calculate the element-wise remainder of the division of `arr1` by `arr2`, storing the result in the `result_remainder` variable.

- `print("Remainder Result:", result_remainder)`: Prints the result of the remainder calculation.

## Quotient and Remainder:
### The divmod() function returns both the quotient and remainder.


Your comment seems to be a bit misleading. The `np.divmod()` function returns both the quotient and the remainder of the element-wise division of two arrays. Here's the corrected comment and code:

```python
# Example of calculating the quotient and remainder of values
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

# Using np.divmod() to calculate element-wise division and remainder of arr1 divided by arr2
result_quotient, result_remainder = np.divmod(arr1, arr2)

# Printing the result of the divmod calculation
print("Quotient Result:", result_quotient)
print("Remainder Result:", result_remainder)
```

Explanation:

- `result_quotient, result_remainder = np.divmod(arr1, arr2)`: Uses the `np.divmod()` function to calculate both the element-wise quotient and remainder of the division of `arr1` by `arr2`, storing the results in `result_quotient` and `result_remainder` variables, respectively.

- `print("Quotient Result:", result_quotient)`: Prints the result of the quotient calculation.

- `print("Remainder Result:", result_remainder)`: Prints the result of the remainder calculation.

## absolute() and abs() - perform the same operation, but it's recommended to use absolute() to avoid confusion with the Python built-in function math.abs().


Your comment mentions "Addition Result," but the operation you are performing is taking the absolute values of the elements in the array using `np.absolute()` (or equivalently `np.abs()`). Here's the corrected comment and code:

```python
# Example of taking the absolute values of elements
import numpy as np

# Creating a NumPy array with negative values
arr1 = np.array([-1, -2, -3, -4, -5])

# Using np.absolute() to calculate element-wise absolute values
result_absolute = np.absolute(arr1)

# Printing the result of the absolute value calculation
print("Absolute Values Result:", result_absolute)
```

Explanation:

- `result_absolute = np.absolute(arr1)`: Uses the `np.absolute()` function to calculate the element-wise absolute values of the elements in `arr1`, storing the result in the `result_absolute` variable.

- `print("Absolute Values Result:", result_absolute)`: Prints the result of the absolute value calculation.

# 33.NumPy Rounding Decimals | trunc() fix() around() floor() ceil() 

NumPy provides several functions for rounding decimals. Here are some commonly used ones:

1. **`np.trunc()`**: Truncates each element of an array to the nearest integer towards 0.

```python
import numpy as np

arr = np.array([1.234, 2.567, -3.789, 4.123])

result_trunc = np.trunc(arr)
print("Truncation Result:", result_trunc)
```

2. **`np.fix()`**: Rounds each element of an array towards 0.

```python
import numpy as np

arr = np.array([1.234, 2.567, -3.789, 4.123])

result_fix = np.fix(arr)
print("Fix Result:", result_fix)
```

3. **`np.around()`**: Rounds each element of an array to the nearest integer, rounding to the even number in the case of a tie.

```python
import numpy as np

arr = np.array([1.234, 2.567, -3.789, 4.123])

result_around = np.around(arr)
print("Rounding Result:", result_around)
```

4. **`np.floor()`**: Rounds each element of an array to the nearest integer less than or equal to it.

```python
import numpy as np

arr = np.array([1.234, 2.567, -3.789, 4.123])

result_floor = np.floor(arr)
print("Floor Result:", result_floor)
```

5. **`np.ceil()`**: Rounds each element of an array to the nearest integer greater than or equal to it.

```python
import numpy as np

arr = np.array([1.234, 2.567, -3.789, 4.123])

result_ceil = np.ceil(arr)
print("Ceiling Result:", result_ceil)
```

These functions offer different rounding strategies depending on your specific use case.

# Sharad
Your code is using the `np.around()` function to round the elements of the array to a specified number of decimals. Here are the results for the provided code:

1. Rounding to 1 decimal place:

```python
import numpy as np

arr = np.array([-3.1666, 3.6667])

result_around = np.around(arr, 1)
print("Rounding Result (1 decimal place):", result_around)
```

Output:
```
Rounding Result (1 decimal place): [-3.2  3.7]
```

2. Rounding to 2 decimal places:

```python
import numpy as np

arr = np.array([-3.1666, 3.6667])

result_around = np.around(arr, 2)
print("Rounding Result (2 decimal places):", result_around)
```

Output:
```
Rounding Result (2 decimal places): [-3.17  3.67]
```

In both cases, the `np.around()` function rounds the elements of the array to the specified number of decimal places.

# 34.NumPy Summations & Cumulative Sum || sum() cumsum() axis=1 
## Summation and Difference:
### Addition is performed between two arguments, whereas summation occurs over n elements.


Certainly! NumPy provides functions for summation and cumulative summation (cumulative sum) operations. Here's how you can use `np.sum()` and `np.cumsum()` with the `axis=1` parameter:

1. **`np.sum()` with `axis=1`**: Calculates the sum along the specified axis (axis=1 for columns).

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Sum along axis 1 (columns)
result_sum_axis1 = np.sum(arr, axis=1)
print("Sum along axis 1:", result_sum_axis1)
```

Output:
```
Sum along axis 1: [ 6 15]
```

2. **`np.cumsum()` with `axis=1`**: Calculates the cumulative sum along the specified axis (axis=1 for columns).

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Cumulative sum along axis 1 (columns)
result_cumsum_axis1 = np.cumsum(arr, axis=1)
print("Cumulative Sum along axis 1:\n", result_cumsum_axis1)
```

Output:
```
Cumulative Sum along axis 1:
 [[ 1  3  6]
 [ 4  9 15]]
```

In the cumulative sum example, each element is the sum of the elements before it (along axis 1). The first element remains the same, the second element is the sum of the first and second elements, and so on.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate the sum of the elements in arr1 and arr2
result_sum = np.sum([arr1, arr2])

# Print the sum result
print("Sum Result:", result_sum)


Sum Result: 21


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate the sum of the elements along axis 0 (element-wise sum)
result_sum_axis0 = np.sum([arr1, arr2], axis=0)
print("Sum Result along axis 0:", result_sum_axis0)

# Calculate the sum of the elements along axis 1 (total sum of each array)
result_sum_axis1 = np.sum([arr1, arr2], axis=1)
print("Sum Result along axis 1:", result_sum_axis1)


Sum Result along axis 0: [5 7 9]
Sum Result along axis 1: [ 6 15]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Calculate the cumulative sum along the array
result_cumsum = np.cumsum(arr)
print("Cumulative Sum along the array:", result_cumsum)


Cumulative Sum along the array: [ 1  3  6 10 15 21 28]


# 35.NumPy Products & Cumulative Product || prod() cumprod() axis=1

Certainly! NumPy provides functions for calculating products and cumulative products. Here's how you can use `np.prod()` and `np.cumprod()` with the `axis=1` parameter for operations along columns:

1. **`np.prod()` with `axis=1`**: Calculates the product along the specified axis (axis=1 for columns).

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Product along axis 1 (columns)
result_prod_axis1 = np.prod(arr, axis=1)
print("Product along axis 1:", result_prod_axis1)
```

Output:
```
Product along axis 1: [  6 120]
```

2. **`np.cumprod()` with `axis=1`**: Calculates the cumulative product along the specified axis (axis=1 for columns).

```python
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Cumulative product along axis 1 (columns)
result_cumprod_axis1 = np.cumprod(arr, axis=1)
print("Cumulative Product along axis 1:\n", result_cumprod_axis1)
```

Output:
```
Cumulative Product along axis 1:
 [[  1   2   6]
 [  4  20 120]]
```

In the cumulative product example, each element is the product of the elements before it (along axis 1). The first element remains the same, the second element is the product of the first and second elements, and so on.