# Numpy Array Reshaping

#### reshaping - means changing the shape of an array ,like adding or removing the elements.


In [1]:
# reshaping from 1-D to 2-D
import numpy as np
sharad = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
sharad1 = sharad.reshape(4, 3) # Row , Colummn
print(sharad1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
praveen =sharad.reshape(3,4)
print(praveen)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# reshping from 1-D to 3-D
import numpy as np
sharad = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
sharad1 = sharad.reshape(2, 3, 2) # Indexing , Row , Column
print(sharad1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
praveen1 = sharad.reshape(2,2,3)

In [5]:
# Return copy or view
import numpy as np
sharad = np.array([1,2,3,4,5,6,7,8])
print("Length of Sharad List :",len(sharad))
print("Sharad:",sharad)
print("Respaping Sharad:",sharad.reshape(2, 4).base)
praveen1 = sharad.reshape(4,2)
print("Reshaping praveen1:\n",praveen1)


Length of Sharad List : 8
Sharad: [1 2 3 4 5 6 7 8]
Respaping Sharad: [1 2 3 4 5 6 7 8]
Reshaping praveen1:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:
# unknown dimension - you are only allowed to have one unknown dimension. pass -1.

import numpy as np
sharad = np.array([1,2,3,4,5,6,7,8])
sharad1 = sharad.reshape(2, 2, -1)
print(sharad1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# Flattening the array by converting multidimensional array in 1-D.
import numpy as np
sharad = np.array([[1,2,3], [4,5,6]])
sharad1 = sharad.reshape(-1)
print(sharad1)

[1 2 3 4 5 6]


In [8]:
# there are alot of functions for changing the shapes pf an array in numpy. like flatten, ravel and also rearranging the element rot90, flip,fliplr, flipud. they all are actually comes under advanced numpy.