# LECTURE 6 : NUMPY ARRAY COPY AND VIEW
The main difference between a copy and a view of a NumPy array is that the copy is a new array, and the view is just a view of the original array. The copy owns the data and any changes made to the copy will not affect the original array, and any changes made to the original array will not affect the copy. The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view1

In [1]:
# Diffrence Numpy array  copy and view

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print("Original array: ", arr)
print("Copy of array: ", x)


Original array:  [42  2  3  4  5]
Copy of array:  [1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print("Original array: ", arr)
print("View of array: ", x)


Original array:  [42  2  3  4  5]
View of array:  [42  2  3  4  5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print("Original array: ", arr)
print("View of array: ", x)


Original array:  [31  2  3  4  5]
View of array:  [31  2  3  4  5]


# LECTURE 7 : ARRAY SHAPE
The shape attribute of a NumPy array returns a tuple of integers representing the size of the array in each dimension. Here is an example:


In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)


Array shape: (2, 3)


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)
print("Shape of original array:", arr.shape)

new_arr = arr.reshape(3, 2)
print("New array:\n", new_arr)
print("Shape of new array:", new_arr.shape)


Original array:
 [[1 2 3]
 [4 5 6]]
Shape of original array: (2, 3)
New array:
 [[1 2]
 [3 4]
 [5 6]]
Shape of new array: (3, 2)


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:\n", arr)
print("Shape of original array:", arr.shape)

new_arr = arr.reshape(2, 3)
print("New array:\n", new_arr)
print("Shape of new array:", new_arr.shape)


Original array:
 [1 2 3 4 5 6]
Shape of original array: (6,)
New array:
 [[1 2 3]
 [4 5 6]]
Shape of new array: (2, 3)


In [7]:
import numpy as np

# Creating a NumPy array with elements 1, 2, 3, 4, 5
arr = np.array([1, 2, 3, 4, 5])

# Getting the shape of the array
shape_of_arr = arr.shape

# Printing the shape of the array
print("Shape of the array:", shape_of_arr)


Shape of the array: (5,)


In [8]:
import numpy as np

# Creating a 2-dimensional NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the shape of the 2D array
shape_of_arr_2d = arr_2d.shape

# Printing the shape of the 2D array
print("Shape of the 2D array:", shape_of_arr_2d)


Shape of the 2D array: (2, 3)


In [9]:
import numpy as np

# Creating a 3-dimensional NumPy array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Getting the shape of the 3D array
shape_of_arr_3d = arr_3d.shape

# Printing the shape of the 3D array
print("Shape of the 3D array:", shape_of_arr_3d)


Shape of the 3D array: (2, 2, 3)


In [10]:
import numpy as np

# Creating a 4-dimensional NumPy array
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

# Getting the shape of the 4D array
shape_of_arr_4d = arr_4d.shape

# Printing the shape of the 4D array
print("Shape of the 4D array:", shape_of_arr_4d)


Shape of the 4D array: (2, 2, 2, 2)


In [11]:
import numpy as np

# Creating a 5-dimensional NumPy array
arr_5d = np.random.rand(2, 3, 4, 5, 6)

# Getting the shape of the 5D array
shape_of_arr_5d = arr_5d.shape

# Printing the shape of the 5D array
print("Shape of the 5D array:", shape_of_arr_5d)


Shape of the 5D array: (2, 3, 4, 5, 6)


In [12]:
import numpy as np
pks5d_arr = np.array([1,2,3,4,5], ndmin=5)
print(pks5d_arr)
print("Shape of the 5D array:", pks5d_arr.shape)

[[[[[1 2 3 4 5]]]]]
Shape of the 5D array: (1, 1, 1, 1, 5)


Here is a summary of the current Topics:

- **Numpy Array Copy and View**: This page explains the difference between copying and viewing a numpy array, and how to perform these operations using various methods.
- **Copy**: A copy is a new array object that has a deep copy of the original array's data. Changes made to the copy will not affect the original array, and vice versa. Copying can be done using the `copy()` method or the `np.copy()` function.
- **View**: A view is an array object that shares the same data as the original array. Changes made to the view will affect the original array, and vice versa. Viewing can be done using slicing, indexing, or the `view()` method.
- **Checking if Arrays Share Data**: To check if two arrays share the same data, one can use the `base` attribute or the `np.shares_memory()` function. The `base` attribute returns the original array if the array is a view, or `None` if the array is a copy. The `np.shares_memory()` function returns `True` if the arrays share data, or `False` otherwise.

# LECTURE 8 : NUMPY ARRAY RESHAPING

NumPy array reshaping is the process of changing the shape of an array without changing its data. The shape of an array is the number of elements in each dimension. By reshaping, we can add or remove dimensions or change the number of elements in each dimension.

To reshape an array, we use the `reshape()` method of the array object or the `np.reshape()` function. The syntax is:

```python
array.reshape(newshape, order='C')
```

or

```python
np.reshape(array, newshape, order='C')
```

where `array` is the input array, `newshape` is a tuple of integers specifying the new shape, and `order` is an optional argument that determines the order of reading and writing the elements. The default order is 'C', which means row-major order. Other possible values are 'F' for column-major order and 'A' for the order of the input array.

The new shape should be compatible with the original shape, meaning that the total number of elements should be the same. One of the dimensions can be -1, which means that the value is inferred from the length of the array and the remaining dimensions.

For example, to reshape a 1D array with 12 elements into a 2D array with 4 rows and 3 columns, we can do:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
```

Output:

```
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```

To reshape a 2D array with 6 elements into a 3D array with 2 arrays, each containing 1 array with 3 elements, we can do:

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(2, 1, 3)
print(newarr)
```

Output:

```
[[[1 2 3]]

 [[4 5 6]]]
```

To reshape an array with an unknown dimension, we can use -1 as a placeholder. For example, to reshape a 1D array with 8 elements into a 2D array with 2 rows and an unknown number of columns, we can do:

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, -1)
print(newarr)
```

Output:

```
[[1 2 3 4]
 [5 6 7 8]]
```

The `reshape()` method returns a new array object with the new shape. However, it does not always create a copy of the data. If the new shape is compatible with the original shape and order, it may return a view of the original array. To check if the returned array is a copy or a view, we can use the `base` attribute, which returns the original array if the array is a view, or None if the array is a copy. For example:

```python
import numpy as np

arr = np.array([1, 2, 3, 4])
newarr = arr.reshape(2, 2)
print(newarr.base)
```

Output:

```
[1 2 3 4]
```

This means that `newarr` is a view of `arr`, and any changes made to `newarr` will affect `arr`, and vice versa.

For more information and examples, you can refer to the [NumPy documentation](^1^) or some online tutorials such as [W3Schools](^2^), [GeeksforGeeks](^3^), or [Programiz](^4^).

Source: Conversation with Bing, 5/1/2024
(1) numpy.reshape — NumPy v1.26 Manual. https://numpy.org/doc/stable/reference/generated/numpy.reshape.html.
(2) NumPy Array Reshaping - W3Schools. https://www.w3schools.com/python/numpy/numpy_array_reshape.asp.
(3) Reshape NumPy Array - GeeksforGeeks. https://www.geeksforgeeks.org/reshape-numpy-array/.
(4) NumPy Array Reshaping (With Examples) - Programiz. https://www.programiz.com/python-programming/numpy/array-reshaping.

## CHTGPT

In [13]:
## Reshape 1D to 2D:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the 1D array to a 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)

# Printing the original and reshaped arrays
print("Original 1D array:\n", arr_1d)
print("\nReshaped 2D array:\n", arr_2d)


Original 1D array:
 [1 2 3 4 5 6]

Reshaped 2D array:
 [[1 2 3]
 [4 5 6]]


In [14]:
# Reshape 1D to 3D:
import numpy as np

# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the 1D array to a 3D array (2 layers, 1 row, 3 columns)
arr_3d = arr_1d.reshape(2, 1, 3)

# Printing the original and reshaped arrays
print("Original 1D array:\n", arr_1d)
print("\nReshaped 3D array:\n", arr_3d)


Original 1D array:
 [1 2 3 4 5 6]

Reshaped 3D array:
 [[[1 2 3]]

 [[4 5 6]]]


In [15]:
# Reshape 2D to 1D:
import numpy as np

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping the 2D array to a 1D array
arr_1d = arr_2d.reshape(-1)

# Printing the original and reshaped arrays
print("Original 2D array:\n", arr_2d)
print("\nReshaped 1D array:\n", arr_1d)


Original 2D array:
 [[1 2 3]
 [4 5 6]]

Reshaped 1D array:
 [1 2 3 4 5 6]


## SHARAD 

In [16]:
import numpy as np

# Creating a 1D NumPy array with elements 1 to 12
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the 1D array to a 2D array with 4 rows and 3 columns
arr_2d = arr.reshape(4, 3)

# Printing the reshaped 2D array
print(arr_2d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
import numpy as np

# Creating a 1D NumPy array with elements 1 to 12
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the 1D array to a 3D array with dimensions 2x3x2
arr_3d = arr.reshape(2, 3, 2)

# Printing the reshaped 3D array
print(arr_3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
import numpy as np

# Creating a 1D NumPy array with elements 1 to 12
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the 1D array to a 2D array with dimensions 6x2
arr_2d = arr.reshape(6, 2)

# Printing the reshaped 2D array
print(arr_2d)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [19]:
import numpy as np

# Creating a 1D NumPy array with elements 1 to 12
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the 1D array to a 2D array with dimensions 6x2
arr_2d = arr.reshape(6, 2)

# Printing the base attribute of the reshaped array
print("Base of the reshaped array:", arr_2d.base  # Note it is the view not copy 


SyntaxError: incomplete input (1443449402.py, line 10)

**In NumPy, you can use -1 as a placeholder for an unknown dimension when reshaping an array. When you use -1, NumPy automatically calculates the size of that dimension based on the total number of elements in the array. However, it's important to note that you can have at most one unknown dimension.**

In [ ]:
import numpy as np

# Creating a 1D NumPy array with elements 1 to 8
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Reshaping the 1D array to a 3D array with dimensions (2, 2, -1)
arr_unknown_d = arr.reshape(2, 2, -1)

# Printing the reshaped 3D array
print(arr_unknown_d)


In [ ]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array to a 1D array using reshape(-1)
arr_1d = arr.reshape(-1)

# Printing the flattened 1D array
print(arr_1d)


### Reshaping Functions:

1. **reshape:** Changes the shape of an array.
    ```python
    arr.reshape((rows, columns))
    ```

2. **flatten:** Returns a 1D array by flattening the input array.
    ```python
    arr.flatten()
    ```

3. **ravel:** Returns a flattened 1D array.
    ```python
    np.ravel(arr)
    ```

### Rearranging Functions:

4. **rot90:** Rotates an array by 90 degrees in the plane specified by axes.
    ```python
    np.rot90(arr, k=1)
    ```

5. **flip:** Reverses the order of elements along a specified axis.
    ```python
    np.flip(arr, axis=0)
    ```

6. **fliplr:** Flips array in the left/right direction.
    ```python
    np.fliplr(arr)
    ```

7. **flipud:** Flips array in the up/down direction.
    ```python
    np.flipud(arr)
    ```

These functions provide flexibility for reshaping, flattening, and rearranging arrays based on specific requirements. You can choose the one that fits your needs the best. For example, `flatten` and `ravel` are similar, but `flatten` returns a copy of the array, while `ravel` returns a flattened view of the original array whenever possible.


In [ ]:
# Example 1 : Reshape
import numpy as np

# Creating a 2D array for examples
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping the array to (3, 2)
reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr)


In [ ]:
# Example 2 : Flatten
import numpy as np

# Creating a 2D array for examples
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_arr = arr.flatten()
print(flattened_arr)


In [ ]:
# Example 3 : Ravel
import numpy as np

# Creating a 2D array for examples
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Raveling the array
flattened_arr = np.ravel(arr)
print(flattened_arr)


In [ ]:
# Example 4 : Rot90
import numpy as np

# Creating a 2D array for examples
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Rotating the array by 90 degrees
rotated_arr = np.rot90(arr)
print(rotated_arr)


# LECTURE 9 : NUMPY ARRAY ITERATING 

**In NumPy, you can iterate over elements of an array using various methods. Here are some common ways to iterate through NumPy arrays:**

In [ ]:
# 1. Using for loop:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for row in arr:
    for element in row:
        print(element)


In [ ]:
# 2. Using nditer:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for element in np.nditer(arr):
    print(element)


In [ ]:
# 3. Using enumerate:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for i, row in enumerate(arr):
    for j, element in enumerate(row):
        print(f"arr[{i}][{j}] = {element}")


In [ ]:
# 4. Using flat attribute:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for element in arr.flat:
    print(element)


## SHARAD